# Generated by Django 5.0.14 on 2025-06-01 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.TextField(unique=True)),
                ("base_experience", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField()),
                ("is_default", models.BooleanField(default=True)),
                ("order", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("forms", models.JSONField(default=list)),
                ("held_items", models.JSONField(default=list)),
                ("location_area_encounters", models.URLField(max_length=500)),
                ("moves", models.JSONField(default=list)),
                ("species_data", models.JSONField(default=dict)),
                ("sprites", models.JSONField(default=dict)),
                ("stats", models.JSONField(default=list)),
            ],
            options={
                "db_table": '"pokeapi"."pokemon"',
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PokemonAbility",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.TextField(unique=True)),
                ("is_main_series", models.BooleanField(default=True)),
                ("generation_id", models.IntegerField(blank=True, null=True)),
                ("effect_entries", models.JSONField(default=list)),
                ("effect_changes", models.JSONField(default=list)),
                ("flavor_text_entries", models.JSONField(default=list)),
            ],
            options={
                "db_table": '"pokeapi"."abilities"',
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.TextField(unique=True)),
                ("damage_relations", models.JSONField(default=dict)),
                ("generation_id", models.IntegerField(blank=True, null=True)),
                ("move_damage_class", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": '"pokeapi"."pokemon_types"',
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PokemonAbilityRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.IntegerField()),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemon_relations",
                        to="pokeapi.pokemonability",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ability_relations",
                        to="pokeapi.pokemon",
                    ),
                ),
            ],
            options={
                "db_table": '"pokeapi"."pokemon_ability_relations"',
                "ordering": ["pokemon", "slot"],
                "unique_together": {("pokemon", "slot")},
            },
        ),
        migrations.AddField(
            model_name="pokemon",
            name="pokemon_abilities",
            field=models.ManyToManyField(
                through="pokeapi.PokemonAbilityRelation", to="pokeapi.pokemonability"
            ),
        ),
        migrations.CreateModel(
            name="PokemonTypeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.IntegerField()),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_relations",
                        to="pokeapi.pokemon",
                    ),
                ),
                (
                    "pokemon_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemon_relations",
                        to="pokeapi.pokemontype",
                    ),
                ),
            ],
            options={
                "db_table": '"pokeapi"."pokemon_type_relations"',
                "ordering": ["pokemon", "slot"],
                "unique_together": {("pokemon", "slot")},
            },
        ),
        migrations.AddField(
            model_name="pokemon",
            name="types",
            field=models.ManyToManyField(
                through="pokeapi.PokemonTypeRelation", to="pokeapi.pokemontype"
            ),
        ),
    ]
